apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource 
metadata:
  name: mysql          # DNS name
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:              
    app: mysql
  clusterIP: None
